# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: lbrlabs-eks
displayName: LBr Labs EKS
publisher: lbrlabs
pluginDownloadURL: "github://api.github.com/lbrlabs"
description: "A batteries included EKS cluster following best practices."
logoUrl: "https://raw.githubusercontent.com/lbrlabs/pulumi-lbrlabs-eks/main/assets/amazon-eks.png" #nolint:golint,lll
keywords:
  - eks
  - kubernetes
  - aws
  - lbrlabs
  - kind/component
  - category/cloud
repository: "https://github.com/lbrlabs/pulumi-lbrlabs-eks"
resources:
  lbrlabs-eks:index:Cluster:
    isComponent: true
    inputProperties:
      letsEncryptEmail:
        type: string
        description: The email address to use to issue certificates from Lets Encrypt.
      clusterSubnetIds:
        type: array
        items:
          type: string
      systemNodeSubnetIds:
        type: array
        items:
          type: string
      systemNodeInstanceTypes:
        type: array
        items:
          type: string
      systemNodeMaxCount:
        type: number
        description: The maximum number of nodes in the system autoscaling group.
      systemNodeMinCount:
        type: number
        description: The minimum number of nodes in the system autoscaling group.
      systemNodeDesiredCount:
        type: number
        description: The initial number of nodes in the system autoscaling group.
    requiredInputs:
      - clusterSubnetIds
      - systemNodeSubnetIds
      - letsEncryptEmail
    properties:
      kubeconfig:
        "type": string
        "description": The kubeconfig for this cluster.
      controlPlane:
        "$ref": "/aws/v5.41.0/schema.json#/resources/aws:eks%2Fcluster:Cluster"
        "description": The Cluster control plane
      oidcProvider:
        "$ref": "/aws/v5.41.0/schema.json#/resources/aws:iam%2FopenIdConnectProvider:OpenIdConnectProvider"
        "description": The OIDC provider for this cluster.
      systemNodes:
        "$ref": "/aws/v5.41.0/schema.json#/resources/aws:eks%2FnodeGroup:NodeGroup"
        "description": The system node group.
      # clusterIssuer:
      #   "$ref": "/kubernetes/v3.29.1/schema.json#/resources/kubernetes:apiextensions.k8s.io:CustomResource"
    required:
      - controlPlane
      - oidcProvider
      - kubeconfig
      - systemNodes
  lbrlabs-eks:index:AttachedNodeGroup:
    isComponent: true
    inputProperties:
      clusterName:
        type: string
        description: The cluster name to attach the nodegroup tp.
      subnetIds:
        type: array
        items:
          type: string
      nodeInstanceTypes:
        type: array
        items:
          type: string
      scalingConfig:
        "$ref": "/aws/v5.41.0/schema.json#/types/aws:eks%2FNodeGroupScalingConfig:NodeGroupScalingConfig"
      taints:
        type: "array"
        items:
          "$ref": "/aws/v5.41.0/schema.json#/types/aws:eks%2FNodeGroupTaint:NodeGroupTaint"
      labels:
        type: object
        additionalProperties:
          type: string
        description: "Key-value map of Kubernetes labels. Only labels that are applied with the EKS API are managed by this argument. Other Kubernetes labels applied to the EKS Node Group will not be managed."
    requiredInputs:
      - clusterName
      - subnetIds
    properties:
      nodeGroup:
        "$ref": "/aws/v5.41.0/schema.json#/resources/aws:eks%2FnodeGroup:NodeGroup"
      nodeRole:
        "$ref": "/aws/v5.41.0/schema.json#/resources/aws:iam%2Frole:Role"
    required:
      - nodeGroup
      - nodeRole
  lbrlabs-eks:index:IamServiceAccountRole:
    isComponent: true
    inputProperties:
      oidcProviderArn:
        type: string
        description: The arn of the OIDC provider attached to your EKS cluster.
      oidcProviderUrl:
        type: string
        description: The URL of the OIDC provider attached to your EKS cluster.
      namespaceName:
        type: string
        description: The namespace to create the service account in.
      serviceAccountName:
        type: string
        description: The name of the service account to bind to the role
    requiredInputs:
      - oidcProviderArn
      - oidcProviderUrl
      - namespaceName
      - serviceAccountName
    properties:
      role:
        "$ref": "/aws/v5.41.0/schema.json#/resources/aws:iam%2Frole:Role"
    required:
      - role
  lbrlabs-eks:index:IamRoleMapping:
    isComponent: true
    inputProperties:
      roleArn:
        type: string
        description: The arn of the role to map to a Kubernetes group.
      username:
        type: string
        description: The username to assign to the rolemapping.
      groups:
        type: array
        items:
          type: string
        description: An array of groups to map the IAM role to.
    requiredInputs:
      - roleArn
      - username
      - groups
    properties:
      roleMapping:
        "$ref": "/kubernetes/v3.29.1/schema.json#/resources/kubernetes:apiextensions.k8s.io:CustomResource"
    required:
      - roleMapping
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 5.*
      Pulumi.Kubernetes: 3.*
    rootNamespace: Lbrlabs.PulumiPackage
    namespaces:
      lbrlabs-eks: "Eks"
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/lbrlabs/pulumi-lbrlabs-eks/sdk/go/eks
  nodejs:
    dependencies:
      "@pulumi/aws": "^5.0.0"
      "@pulumi/kubernetes": "^3.0.0"
    devDependencies:
      typescript: "^3.7.0"
    packageName: "@lbrlabs/pulumi-eks"
  python:
    packageName: "lbrlabs_pulumi_eks"
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-aws: ">=5.0.0,<6.0.0"
      pulumi-kubernetes: ">=3.0.0,<4.0.0"
