apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  tolerations:
  - key: "node.lbrlabs.com/system"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
